### ISSUE TITLE
Directions explicitly state that help should be called, but tests are not written based on that assumption

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/cli-applications-jukebox#1]
The first step of the `run` method for this lab is to call the `help` method. However, some tests in the "with commands" section are not assuming that the `help` method will be called first, so they fail.

**Comment by maxwellbenton** [comment]
Hey @kwebster2,

I've removed that first step in the directions so that the readme aligns with the tests.

Thank you for catching this and reporting!
